# Generated by Django 5.1.6 on 2025-04-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse_maison", models.CharField(max_length=200)),
                ("nom_maison", models.CharField(max_length=100)),
                ("mot_de_passe", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_piece", models.CharField(max_length=200)),
                (
                    "id_maison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.maison",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lampe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etat", models.BooleanField(default=False)),
                ("nom_lampe", models.CharField(max_length=200)),
                (
                    "id_piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.piece"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("mot_de_passe", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("tel", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "id_maison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="main_app.maison",
                    ),
                ),
            ],
        ),
    ]
