# Generated by Django 5.1.6 on 2025-04-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_link_maison_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maison",
            name="id_user",
        ),
    ]
