# Generated by Django 5.1.6 on 2025-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_remove_maison_id_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maison",
            name="points",
        ),
        migrations.AddField(
            model_name="link_maison_user",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="link_maison_user",
            name="valid_mail",
            field=models.BooleanField(default=False),
        ),
    ]
