# Generated by Django 5.1.6 on 2025-04-11 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_remove_maison_points_link_maison_user_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="link_maison_user",
            old_name="id_User",
            new_name="id_user",
        ),
        migrations.AddConstraint(
            model_name="link_maison_user",
            constraint=models.UniqueConstraint(
                fields=("id_maison", "id_user"), name="unique_ids"
            ),
        ),
    ]
