# Generated by Django 5.1.6 on 2025-04-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_rename_id_user_link_maison_user_id_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link_maison_user",
            name="id",
        ),
        migrations.AlterField(
            model_name="link_maison_user",
            name="id_maison",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="main_app.maison",
            ),
        ),
    ]
