# Generated by Django 5.1.6 on 2025-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_remove_link_maison_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lampe",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="piece",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
